// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5OfLuRW1A4H15jGnjLrLOJRBOjZPvGA',
    appId: '1:286818601377:web:8ee6314cd5ea69dd3de3e0',
    messagingSenderId: '286818601377',
    projectId: 'eventmanagementsystem-99e2a',
    authDomain: 'eventmanagementsystem-99e2a.firebaseapp.com',
    storageBucket: 'eventmanagementsystem-99e2a.firebasestorage.app',
    measurementId: 'G-FHTLTTFTLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAocj5UOlSPsBiZ06mKfFUsjrUldyOuVE0',
    appId: '1:286818601377:android:df3a6e9a054c6ccc3de3e0',
    messagingSenderId: '286818601377',
    projectId: 'eventmanagementsystem-99e2a',
    storageBucket: 'eventmanagementsystem-99e2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl22ETtEEoS6r-IL8UT_7EYsfWYq_V8vs',
    appId: '1:286818601377:ios:2ab6c55d31e692ae3de3e0',
    messagingSenderId: '286818601377',
    projectId: 'eventmanagementsystem-99e2a',
    storageBucket: 'eventmanagementsystem-99e2a.firebasestorage.app',
    androidClientId: '286818601377-6lp178h387m48sp7seplfksopihm6ssu.apps.googleusercontent.com',
    iosClientId: '286818601377-5664i8gmh3fioie47bqt10neqith989u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl22ETtEEoS6r-IL8UT_7EYsfWYq_V8vs',
    appId: '1:286818601377:ios:2ab6c55d31e692ae3de3e0',
    messagingSenderId: '286818601377',
    projectId: 'eventmanagementsystem-99e2a',
    storageBucket: 'eventmanagementsystem-99e2a.firebasestorage.app',
    androidClientId: '286818601377-6lp178h387m48sp7seplfksopihm6ssu.apps.googleusercontent.com',
    iosClientId: '286818601377-5664i8gmh3fioie47bqt10neqith989u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy5OfLuRW1A4H15jGnjLrLOJRBOjZPvGA',
    appId: '1:286818601377:web:4f004c94730dc2073de3e0',
    messagingSenderId: '286818601377',
    projectId: 'eventmanagementsystem-99e2a',
    authDomain: 'eventmanagementsystem-99e2a.firebaseapp.com',
    storageBucket: 'eventmanagementsystem-99e2a.firebasestorage.app',
    measurementId: 'G-7FTTRMFGQN',
  );
}
